// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5A3I7KZFiscO60zpkQOJ8SuT0DtXr8C0',
    appId: '1:1032076938003:web:de13e47cce7d918494a8e6',
    messagingSenderId: '1032076938003',
    projectId: 'newq-9309f',
    authDomain: 'newq-9309f.firebaseapp.com',
    storageBucket: 'newq-9309f.firebasestorage.app',
    measurementId: 'G-CQNHWLEE5Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdNBWori08CTTjh5niEnZQp4FeNByEsbY',
    appId: '1:1032076938003:android:809da1e37dc6d50794a8e6',
    messagingSenderId: '1032076938003',
    projectId: 'newq-9309f',
    storageBucket: 'newq-9309f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAP8zOjqrnf6oZTVzLEi2bL_jh7Ha9a5LI',
    appId: '1:1032076938003:ios:a8370ea13f3f287394a8e6',
    messagingSenderId: '1032076938003',
    projectId: 'newq-9309f',
    storageBucket: 'newq-9309f.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication7',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAP8zOjqrnf6oZTVzLEi2bL_jh7Ha9a5LI',
    appId: '1:1032076938003:ios:a8370ea13f3f287394a8e6',
    messagingSenderId: '1032076938003',
    projectId: 'newq-9309f',
    storageBucket: 'newq-9309f.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication7',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5A3I7KZFiscO60zpkQOJ8SuT0DtXr8C0',
    appId: '1:1032076938003:web:d39bf0d5b4b8480b94a8e6',
    messagingSenderId: '1032076938003',
    projectId: 'newq-9309f',
    authDomain: 'newq-9309f.firebaseapp.com',
    storageBucket: 'newq-9309f.firebasestorage.app',
    measurementId: 'G-6GN8800GZR',
  );
}
